### ISSUE TITLE
go: cannot find main module, but found .git/config in /github/workspace

### ISSUE THREAD

**Issue by sarnobat** [sosedoff/actions#3]
I'm new to Github actions, and cannot get a go build Github action to work for a hello world program.

Could you point me in the right direction? 

### My code
(Mostly copied and pasted from the readme)
```
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.24
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
```
https://github.com/sarnobat/github_workflow_action_tutorial/blob/main/.github/workflows/release.yml

### Error
```
go build -o build-artifacts-1643616945/github_workflow_action_tutorial ''
go: cannot find main module, but found .git/config in /github/workspace
	to create a module there, run:
	go mod init
```
When I execute the failing command on my local mac (without any environment variables set), it works. 

### Full Log
This is my latest of many failed attempts (not sure if you are able to view):
https://github.com/sarnobat/github_workflow_action_tutorial/runs/5002856979?check_suite_focus=true
